name: Auto Build Linux Kernel on Push

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-kernel:
    name: Compile Linux Kernel
    runs-on: ubuntu-latest

    env:
      ARCH: "x86_64"
      KERNEL_CONFIG: "arch/x86/configs/x86_64_defconfig"
      BUILD_OUTPUT_DIR: "kernel-build"
      COMPILER: "gcc"

    steps:
      - name: Checkout Linux Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            flex bison libssl-dev \
            libelf-dev bc cpio \
            git dwarves zstd

      - name: Configure Kernel
        run: |
         make mrproper
         mkdir -p ${{ env.BUILD_OUTPUT_DIR }}
         cp ${{ env.KERNEL_CONFIG }}  ./.config
         cp ./.config ${{ env.BUILD_OUTPUT_DIR }}/result.config
    

      - name: Build Kernel
        run: |
          make -j$(nproc) O=${{ env.BUILD_OUTPUT_DIR }}

      - name: Archive Kernel Artifacts
        run: |
          cd ${{ env.BUILD_OUTPUT_DIR }}
          tar -zcf ../kernel-${{ env.ARCH }}.tar.gz \
            arch/x86/boot/bzImage vmlinux System.map result.config

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ env.ARCH }}-${{ github.sha }}
          path: |
            kernel-${{ env.ARCH }}.tar.gz
