name: Auto Build Linux Kernel on Push

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-kernel:
    name: Compile Linux Kernel
    runs-on: ubuntu-latest

    env:
      ARCH: "x86_64"
      KERNEL_CONFIG: "arch/x86/configs/x86_64_defconfig"
      COMPILER: "gcc"

    steps:
      - name: Checkout Linux Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            flex bison libssl-dev \
            libelf-dev bc cpio \
            git dwarves

      - name: Prepare Build Directory
        run: |
          make mrproper

      - name: Configure Kernel
        run: |
          cp ${{ env.KERNEL_CONFIG }}  ./.config
          make olddefconfig  ARCH=${{ env.ARCH }}
          cp ./.config ./result.config

      - name: Build Kernel
        run: |
          make -j$(($(nproc)*2)) ARCH=${{ env.ARCH }} \
            V=1 2>&1 | tee build.log 

      - name: Archive Kernel Artifacts
        run: |
          tar -zcf ./kernel-${{ env.ARCH }}.tar.gz \
            arch/x86/boot/bzImage \
            vmlinux \
            System.map \
            result.config \
            modules.builtin \
            build.log


      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ env.ARCH }}-${{ github.sha }}
          path: |
            kernel-${{ env.ARCH }}.tar.gz
